"""start

Revision ID: 772194b1f5aa
Revises: 
Create Date: 2021-10-26 18:06:07.259633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '772194b1f5aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats_settings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chat_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_name')
    )
    op.create_table('users_settings',
    sa.Column('id', postgresql.UUID(as_uuid=True),  nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timezone', sa.Float(), nullable=False),
    sa.Column('password', sa.String(), server_default='password', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_chat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_chat')
    op.drop_table('messenges')
    op.drop_table('users_settings')
    op.drop_table('chats_settings')
    # ### end Alembic commands ###



# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('chats_settings',
#                     sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
#                     sa.Column('chat_name', sa.String(length=255), nullable=False),
#                     sa.PrimaryKeyConstraint('id'),
#                     sa.UniqueConstraint('chat_name')
#                     )
#     op.create_table('users_settings',
#                     sa.Column('id', sa.Integer(),autoincrement=True,  nullable=False),
#                     sa.Column('username', sa.String(), nullable=False),
#                     sa.Column('timezone', sa.Float(), nullable=False),
#                     sa.Column('password', sa.String(), server_default='password', nullable=False),
#                     sa.PrimaryKeyConstraint('id')
#                     )
#     op.create_table('messenges',
#                     sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
#                     sa.Column('text', sa.String(), nullable=False),
#                     sa.Column('user_id', sa.Integer(), nullable=False),
#                     sa.Column('chat_id', sa.Integer(), nullable=False),
#                     sa.Column('send_time', sa.DateTime(), nullable=True),
#                     sa.ForeignKeyConstraint(['chat_id'], ['chats_settings.id'], ondelete='CASCADE'),
#                     sa.ForeignKeyConstraint(['user_id'], ['users_settings.id'], ondelete='CASCADE'),
#                     sa.PrimaryKeyConstraint('id')
#                     )
#     op.create_table('users_chat',
#                     sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
#                     sa.Column('chat_id', sa.Integer(), nullable=False),
#                     sa.Column('user_id', sa.Integer(), nullable=False),
#                     sa.ForeignKeyConstraint(['chat_id'], ['chats_settings.id'], ondelete='CASCADE'),
#                     sa.ForeignKeyConstraint(['user_id'], ['users_settings.id'], ondelete='CASCADE'),
#                     sa.PrimaryKeyConstraint('id')
#                     )
#     # ### end Alembic commands ###
#
#
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('users_chat')
#     op.drop_table('messenges')
#     op.drop_table('users_settings')
#     op.drop_table('chats_settings')
#     # ### end Alembic commands ###
